{% set name = "pyseobnr" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyseobnr-{{ version }}.tar.gz
  sha256: d276181efc3a03801dbc58fcd7cf674482f4a2948c4d1dac164b6ee142f23bba

build:
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - numpy
    - pip
    - python
    - scipy
    - setuptools
    - setuptools-scm >=3.4.3
    - wheel
  run:
    - h5py
    - jax
    - jaxlib
    - matplotlib-base
    - numba
    - numexpr
    - pygsl_lite
    - python
    - python-lal
    - python-lalinference
    - python-lalsimulation
    - qnm
    - rich
    - scipy >=1.8.0
    - scri
    - setuptools
    - {{ pin_compatible('numpy') }}
    - numpy >=1.23.0

test:
  requires:
    - pip
    - pytest
  source_files:
    - test/
  commands:
    #- python -m pip check
    # This is disabled becase scri and sxs have issues on pypi
    - python -m pip show pyseobnr
    - python -m pytest test/ -ra

about:
  summary: Gravitational wave modelling within the effective-one-body framework
  license: GPL-3.0-or-later
  license_file: LICENSE
  home: https://git.ligo.org/waveforms/software/pyseobnr
  dev_url: https://git.ligo.org/waveforms/software/pyseobnr
  doc_url: https://waveforms.docs.ligo.org/software/pyseobnr/

extra:
  recipe-maintainers:
    - SergeiOssokine
    - duncanmmacleod
    - lorenzopompili00
